name: setragestion
description: "Flutter project for employee management"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ðŸ” Auth & HTTP
  http: ^1.5.0
  flutter_secure_storage:

  # ðŸ§  State management
  provider:

  # ðŸž Toast messages
  fluttertoast:

  # ðŸ•’ Gestion des dates
  intl:

  # ðŸ’Ž IcÃ´nes & UI
  cupertino_icons:
  font_awesome_flutter:

  # ðŸ§¾ Logs & routing
  logger: ^2.6.2
  go_router:

  # âœ¨ Animations
  animations:

  # ðŸ”Œ Socket.IO
  socket_io_client:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:
  json_serializable:

flutter:
  uses-material-design: true
